name: Android CI Build (Bulut Derleme)

on:
  push:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Projeyi İndir
      uses: actions/checkout@v4 

    - name: 2. JDK (Java) Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' 

    - name: 3. Gradlew Oluşturma ve İzin Verme
      run: |
        chmod +x ./gradlew
        ./gradlew wrapper --gradle-version 8.6

    - name: 4. APK Derleme (Assemble Debug)
      run: ./gradlew assembleDebug

    - name: 5. APK'yı İndirilebilir Dosya Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: CanliTV-APK-Derleme
        path: app/build/outputs/apk/debug/app-debug.apk
